export const ActionTypes = {
  // error handling action types
  CLEAR_ERRORS: "CLEAR_ERRORS",
  RETURN_ERRORS: "RETURN_ERRORS",
  // loaders
  ACTION_SHOW_LOADER: "ACTION_SHOW_LOADER",
  // user-related action types
  RETRIEVE_USER_INFO_SUCCESS: "RETRIEVE_USER_INFO_SUCCESS",
  RETRIEVE_USER_INFO_FAIL: "RETRIEVE_USER_INFO_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
};
